name: David Alberto Adler
markdown: kramdown
highlighter: 'rouge'
url: 'https://davidalbertoadler.com'
# pygments: true
plugins:
  - jekyll-sitemap
exclude: [node_modules/, README.md. convert-extracts.sh, gulpfile.js, _scss/, vendor]
collections:
  projects:
    output: true
sass:
  sass_dir: _scss

